[project]
name = "check-cross-lingual-phoneme-map"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "cmudict>=1.1.2",
    "epitran>=1.34.0",
    "matplotlib>=3.10.8",
    "numpy>=2.4.0",
    "panphon>=0.22.2",
    "pyopenjtalk>=0.4.1",
    "scipy>=1.16.3",
    "seaborn>=0.13.2",
]
